### ISSUE TITLE
[PROD][STAGING] User media files not downloading in zip file

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-backend#1291] opened 2022-07-22 13:12 UTC
Preconditions:
The user is logged in to the mobile app.
The user has activity with media items.

Steps to reproduce:
1. Pass the "activity" by downloading media files in items.
2. Go to the https://admin-staging.mindlogger.org/
3. Export data from the "Users page"
4. Extract zip file with media files.
5. Pay attention to the screen.

Actual result:
User media files not downloading in the zip file

Expected result:
User media files are downloaded in the zip file

Video:
https://www.screencast.com/t/Pfggxb5nbGD

Additional screenshot:
**403 error is shown after tapping on the "Export data" button**
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/84ed044f-0099-41df-80a4-6132905bc625)

Environment:
Win 10 // Chrome 103
https://admin-staging.mindlogger.org/
ml_general_acc@protonmail.com / 12345678
media applet 
applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-07-25 13:56
The issue is still reproducible on prod and staging: https://www.screencast.com/t/7OANs5aE

**Comment by natalia-muzyka** [comment] 2022-08-01 06:58
the issue is fixed on staging, but still reproducible on prod:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/67111070-7625-48d5-92aa-4f4e1aab8227)

Environment:
Win 10 // Chrome 103
https://admin.mindlogger.org/
test-user1@com.us	/ qwerty
media applet, media applet 2
test-user2@com.us	/ 123456
media applet
applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-08-01 11:35
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/185bd1ff-8275-4c94-86c8-d75445140ba0)

**Closed by natalia-muzyka** 2022-08-01 11:35 UTC
Labels: bug, Highest
