### ISSUE TITLE
create open invite url

### ISSUE THREAD

**Issue by BarrySunderland** [ChildMindInstitute/mindlogger-backend#1074] opened 2021-06-10 07:43 UTC
issue linked to #843 in mindlogger-admin https://github.com/ChildMindInstitute/mindlogger-admin/issues/843 

Ability for an admin to create an invite url that any logged in ML user can use to add themselves to a study (i.e. create a profile in that study).

**Comment by natalia-muzyka** [comment] 2021-07-19 14:46
1) The user is redirected to the "Get started"/"Log in" page after entering an invite link
Link: web-staging.mindlogger.org/#/join/bcb13d83-bd5e-4a72
Video: https://www.screencast.com/t/WRgMEhvcp5S
This is caused by the extra symbols known [issue](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1055)

2) [UX] Secret user id for the self-invited user isn't comfortable to read
https://www.screencast.com/t/SKl46erc

3) After deleting the invite link the "Accept" and "Decline" buttons are still presented on the invitation page. 
User is able to accept the invitation but the applet won't be added to the user's account and the user won't be shown up on the applet's "Users" tab
Video: https://www.screencast.com/t/FFYtzJyvQYnc

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124 
account owners:
geria.test@gmail.com // 123456
geria1.test@gmail.com // 7clCm7D5
applets:
Healthy Brain Network (NIMH content) edited geria
invite link applet

**Comment by WorldImpex** [comment] 2021-07-19 15:07
@BarrySunderland Could you look into these? We can create separate tickets but it might be easier to just keep this all in one ticket for now.

**Comment by natalia-muzyka** [comment] 2021-07-22 10:08
With a new implementation the "public link" functionality is broken (using the public link that requires creating an account/logging in):

1) The shared applet isn't added to the applet list(isn't shown) after logging in via the public link	
https://www.screencast.com/t/4WDxUBEPKiHG

2) The shared applet isn't added to the applet list(isn't shown) after signing up via the public link	https://www.screencast.com/t/KsAZC3hJ8

3) The "Get started" page is displayed for the already logged-in user after opening the public link.
After clicking the "Get started" button the applet isn't shown up.
https://www.screencast.com/t/5qXj17KZ7zF

4) The "Get started" page is displayed for the logged-in user after opening the deleted public link.
Expected: The message about the entered invitation link is not existing or is deleted.
https://www.screencast.com/t/uE7k3lHT

5) The "Log in" page is displayed for the non-logged-in user after opening the deleted public link.
Expected: The message about the entered invitation link is not existing or is deleted.
https://www.screencast.com/t/IlIU5qSYv

**Comment by peterpeterparker** [comment] 2021-07-27 16:04
1. Issue is not related to this PR. The exact same behavior can be reproduced with a standard applet invitation

**Comment by peterpeterparker** [comment] 2021-07-27 16:08
1. Issue is not related to this PR. The exact same behavior can be reproduced with a standard applet invitation

2. Likewise. Not related to this PR.

3. Likewise. Not related to this PR.

4. The PRs provided last week ([#39](https://github.com/ChildMindInstitute/mindlogger-web/pull/39) and [#38](https://github.com/ChildMindInstitute/mindlogger-web/pull/38) have not been merged

5. It's the expected behavior

6. @BarrySunderland can you have a look to that one?

**Comment by WorldImpex** [comment] 2021-07-27 16:13
So how do you want your users to take an assessment? 1-3 is how the user after accepting the invitation sees the applet. 

5. Leaves the user at a dead end without any explanation.

**Comment by peterpeterparker** [comment] 2021-07-27 16:24
As I said, 1 to 3 can be reproduced with standard nominative applet's invitations too, therefore not related to this PR but a general behavior of the web app.

Regarding 5., again, the behavior matches the open source code we provided.

I pinged Wil and Arno with these findings.

**Comment by WorldImpex** [comment] 2021-07-28 09:54
After removing # from the URL of this public link feature, any account that signs into webapp is shown an invitation. The user can decline it but the URL still shows up at first login the next time the user logs in 

https://images.zenhubusercontent.com/103405378/4d24f76b-db54-47c5-a4c4-a9271911e33f/mindlogger_admin.mp4

**Comment by peterpeterparker** [comment] 2021-07-29 07:24
I have analyzed again the above QA reported issues.

### Summarized

These "issues" are all linked to the same root cause. The URL used for testing purpose contained a **#** which is not the expected URL scheme of the web app. The URLs should not contains a hash. This has been recently corrected in the web app for "nominative applets" but, which has not been corrected for "public invitation applets"

### Details

If correct links are used, there are no issues. Here the details and video as proof.

All videos have been recorded on your staging environment Thursday Jul. 29 early Morning in Switzerland.

1. The "public invitation applet" is **successfully** added to the applet list after logging in. See [screencast](https://www.dropbox.com/s/u8pb9my0evyqnl1/signin-and-accept.mov?dl=0)

2. The "public invitation applet" is **successfully** added to the applet list after sign up. See [screencast](https://www.dropbox.com/s/jyrozo5iyyftbag/signup-and-accept.mov?dl=0)

3. The "public invitation applet" page is displayed when a correct URL is used. See above screencasts.

4. If a "public invitation" link is deleted, the user gets a message that it has been deleted or that he/she using an invalid URL. See [screencast](https://www.dropbox.com/s/dfq85szxa6g88ug/link-not-active.mov?dl=0)

5. This is the expected behavior provided by our open source code

6. Data are **successfully** displayed in the admin panel after completing the assessment. See [screencast](https://www.dropbox.com/s/2x4nhet91o5zkc0/data.mov?dl=0)

### Fix

To solve the situation, we are providing following Pull Request.

The root case being the misused of web app links containing hash, the PR [#1165](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1165) has for goal to remove the hash from the generated links in the admin application

### Goodie

When I tested and recorded above screencast, I noticed that I was redirected to the "public invitation link" after logout and log in again. This is the same behavior as for "nominative applet" which, I find not well suited for such invitation. As I noticed a quick win, I provided two PRs (two for two branches) [#65](https://github.com/ChildMindInstitute/mindlogger-web/pull/65) and [#64](https://github.com/ChildMindInstitute/mindlogger-web/pull/64) in the web app to make the UX behavior feels more natural.

**Comment by natalia-muzyka** [comment] 2021-08-02 09:21
@WorldImpex

1) After the latest changes (#64) the user isn't redirected to the invitation page after signing up/signing in:

signing up:
https://www.screencast.com/t/t43EFf5jRYL

signing in:
https://www.screencast.com/t/mhjycLlo9

2) Waiting for #65 PR (invitation link still contains #)

**Comment by peterpeterparker** [comment] 2021-08-02 15:27
> After the latest changes (➕ Owner Role #64) the user isn't redirected to the invitation page after signing up/signing in .....

Indeed it is a side effect of the two PRs in web app [#65](https://github.com/ChildMindInstitute/mindlogger-web/pull/65) and [#64](https://github.com/ChildMindInstitute/mindlogger-web/pull/64) recently merged.

As we had to remove the persistence of the `redirectUrl` in the state management, if the user is not yet signed in, the redirect cannot happens has there is no where to redirect.

Meanwhile, the above listed PRs are valid to avoid the mambo jambo errors with the join page and linked to handling redirect urls with a store.

Therefore here two new PRs [#80](https://github.com/ChildMindInstitute/mindlogger-web/pull/80) and [#81](https://github.com/ChildMindInstitute/mindlogger-web/pull/81) for the web app which redirect to the `join` page after sign in / up without using the state management.

**Comment by natalia-muzyka** [comment] 2021-08-03 07:47
**The issues are fixed:**
The # is removed from the invitation link,
The user is automatically redirected to the invitation page after sign-in/sign up via a public link that requires a login.
Video: https://www.screencast.com/t/idOFYkP1OR5v

**Closed** 2021-08-03 12:25 UTC
Labels: CMI Milestone 6
